ruction at distance = {d2:.3f} m")
        self.ax.axis('off')
        self.canvas.draw()
        self.ax.set_title(f"Reconstruction at d = {d2:.3f} m")
        self.ax.axis('off')
        self.canvas.draw()